name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2027_alpha5-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew build
